version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_HOST=0.0.0.0
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=bs_data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: BackEnd
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:123456@db:5432/bs_data?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "/usr/local/bin/wait-for-it db:5432 -- npx prisma migrate deploy && npm run start:prod"